name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  detectonly:
    name: Detect use of .only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Detect use of .only
        run: |
          grep -rq --include '*.spec.js' \.only\( . && echo 'You have .only() in your tests!' && exit 1
          exit 0
  chromeheadless:
    name: Chrome headless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Chrome headless
        run: |
          wget https://bellard.org/quickjs/quickjs-2024-01-13.tar.xz
          tar -xf quickjs-2024-01-13.tar.xz
          rm quickjs-2024-01-13.tar.xz
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          npm i -g wasm-opt
          (cd wasmlib && source ../emsdk/emsdk_env.sh && ./build.sh)          
          cd web
          yarn install
          yarn playwright install
          sudo yarn playwright install-deps
          yarn createdevaccount
          yarn test
  distbundle:
    name: Dist bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Chrome headless
        run: |
          cd web
          yarn install
          yarn dist